# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false  # default is true
contact_links:
- name: Feature Request, UX issue or bug?
  url: https://github.com/pypa/warehouse/issues/new/choose
  about: Please open these under `pypa/warehouse`
- name: Security Policy
  url: https://pypi.org/security/
  about: Please learn how to report security vulnerabilities here
- name: PSF Code of Conduct
  url: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
  about: For all Code of Conduct related matters, please refer to this document.
